/**
 * #7-a 6 — exception-processor recovery for infra_transient(quality_evidence_unknown).
 *
 * #6-fix (Codex gate): recovery must enumerate the REQUIRED artifacts (cover + every page), NOT just the
 * existing evidence rows. For each required artifact whose evidence is MISSING, stale, hash-mismatched vs the
 * CURRENT delivered bytes (presentationUrl ?? url), or evidence_unknown → re-QA the CURRENT delivered bytes
 * (ZERO renders — inspectAsset + evaluatePageVisualQa on the stored URL) and persist a fresh verdict bound to
 * the current hash (the persist preserves the DB-reserved regenCount). This recovers a RECOVERABLE current
 * image (a crash-envelope missing row, or a stale PASS row that no longer matches the swapped bytes) instead of
 * refunding it. The refreshed verdicts then feed the recommit (resolve / quality_failed upgrade / re-block) and
 * the regen-rescue (a failed artifact with budget remaining is regenerated by the processor).
 */
import type { PrismaClient } from '@prisma/client';
import { inspectAsset } from './asset-integrity';
import { evaluatePageVisualQa } from './page-visual-qa';
import {
  persistDeliveredQualityEvidence,
  type QaContext,
  type ProducerDeps,
} from './quality-evidence-producer';
import {
  QUALITY_EVALUATOR_CONTRACT_VERSION,
  coverArtifactKey,
  pageArtifactKey,
  pageNumberFromArtifactKey,
  readActiveVisualContractHash,
  resolveArtifactHoldOutcome,
  type HardHoldKind,
} from './quality-evidence';
import { isQualityEvidenceContractStale } from './quality-check-result';
import {
  readFrozenVisualContract,
  contractPageWorldExpectation,
  isVisualContractSteeringEnabled,
  type ContractPageWorldExpectation,
} from '@/lib/visual-contract-compiler';
import type { PipelineCache } from './types';

export interface QualityRecoveryResult {
  reQaCount: number;
  nowPassed: string[];
  /** artifacts that re-QA'd to a deterministic FAIL, with their durable regenCount (drives the regen-rescue). */
  nowFailed: Array<{ artifactKey: string; regenCount: number }>;
  /**
   * (Slice A / Stage 1) artifacts that re-QA'd to a HARD-HOLD reason — a contract-world drift (`contract_world:`) or
   * a physical-safety hazard (`safety:`). These are a TERMINAL human-QA hold — they must NEVER be
   * reserved/cleared/redriven or refunded; the processor resolves the case as parked. Kept OUT of nowFailed.
   */
  nowParked: string[];
  /** (Fix 5) The KIND of the parked hold, driving a distinct marker downstream. Safety DOMINATES contract_world. */
  nowParkedKind: HardHoldKind | null;
  stillUnknown: string[];
}

interface RequiredArtifact {
  artifactKey: string;
  deliveredUrl: string;
}

/** The REQUIRED artifacts with CURRENT delivered bytes: cover (GeneratedBook.coverImageUrl) + each page
 *  (imageAsset.presentationUrl ?? url). Artifacts with no bytes yet are the integrity gate's concern, not QA. */
async function loadRequiredArtifacts(prisma: PrismaClient, orderId: string): Promise<RequiredArtifact[]> {
  const order = await prisma.order.findUnique({
    where: { id: orderId },
    select: {
      book: {
        select: {
          coverImageUrl: true,
          pages: {
            orderBy: { pageNumber: 'asc' },
            select: { pageNumber: true, imageAsset: { select: { url: true, presentationUrl: true } } },
          },
        },
      },
    },
  });
  const out: RequiredArtifact[] = [];
  const cover = order?.book?.coverImageUrl?.trim();
  if (cover) out.push({ artifactKey: coverArtifactKey(), deliveredUrl: cover });
  for (const p of order?.book?.pages ?? []) {
    const url = (p.imageAsset?.presentationUrl ?? p.imageAsset?.url)?.trim();
    if (url) out.push({ artifactKey: pageArtifactKey(p.pageNumber), deliveredUrl: url });
  }
  return out;
}

/**
 * (Slice A) The per-page WORLD expectation from the order's FROZEN contract, keyed by artifactKey — so a recovery
 * re-QA runs world QA too (a pre-change steered `passed` row, re-QA'd under qa-v2, is judged against its contract
 * setting + recurring-object identities, not just visually). Gated on VISUAL_CONTRACT_STEERING + a frozen contract
 * (mirrors the render seam); empty otherwise → recovery re-QA is visual-only (legacy/steering-off parity).
 */
async function loadPageWorldExpectations(
  prisma: PrismaClient,
  orderId: string,
): Promise<Map<string, ContractPageWorldExpectation>> {
  const out = new Map<string, ContractPageWorldExpectation>();
  if (!isVisualContractSteeringEnabled()) return out;
  const job = await prisma.generationJob.findUnique({ where: { orderId }, select: { pipelineCache: true } });
  const cache = (job?.pipelineCache ?? null) as PipelineCache | null;
  const contract = cache ? readFrozenVisualContract(cache.visualContract) : null;
  if (!contract) return out;
  for (const pc of contract.pageContracts) {
    const world = contractPageWorldExpectation(contract, pc.pageNumber);
    if (world) out.set(pageArtifactKey(pc.pageNumber), world);
  }
  return out;
}

export async function reQaUnknownQualityEvidence(
  prisma: PrismaClient,
  orderId: string,
  deps: ProducerDeps = {},
): Promise<QualityRecoveryResult> {
  const inspect = deps.inspect ?? inspectAsset;
  const required = await loadRequiredArtifacts(prisma, orderId);
  const rows = await prisma.qualityEvidence.findMany({
    where: { orderId },
    select: { artifactKey: true, verdict: true, evaluatorContractVersion: true, assetSha256: true, regenCount: true, evidence: true, contractHash: true, reason: true, safetyOverride: true, safetyOverrideSha256: true },
  });
  const byKey = new Map(rows.map((r) => [r.artifactKey, r]));
  // (WS0b B1) Recovery re-QAs STORED bytes and re-binds evidence to the Order's CURRENT active contract, so a
  // contract_stale row becomes admissible again. This is the deliberate recovery re-bind (not a render-time
  // capture) — the render-seam producer threads its render-time hash instead; only THAT post-render read raced.
  const activeContractHash = await readActiveVisualContractHash(prisma, orderId);
  // (Slice A) Per-page world expectation so the recovery re-QA runs world QA (a pre-change steered `passed` row is
  // judged against its contract setting/objects under qa-v2, not just visually). Empty when steering off / no contract.
  const worldByArt = await loadPageWorldExpectations(prisma, orderId);

  const result: QualityRecoveryResult = { reQaCount: 0, nowPassed: [], nowFailed: [], nowParked: [], nowParkedKind: null, stillUnknown: [] };
  // Record a park + fold its kind in (safety dominates across artifacts). The KIND comes from the SHARED
  // resolveArtifactHoldOutcome — never re-derived from the reason here — so recovery and the gate agree on it.
  const notePark = (artifactKey: string, kind: HardHoldKind) => {
    result.nowParked.push(artifactKey);
    if (result.nowParkedKind !== 'safety') result.nowParkedKind = kind;
  };
  for (const art of required) {
    const currentHash = (await inspect(art.deliveredUrl)).sha256;
    const row = byKey.get(art.artifactKey);
    // Admissible = a durable passed/failed verdict on the CURRENT bytes at the current evaluator version. Anything
    // else (missing row, stale version, hash mismatch vs current bytes, or evidence_unknown) is re-QA'd.
    const admissible =
      !!row &&
      row.evaluatorContractVersion === QUALITY_EVALUATOR_CONTRACT_VERSION &&
      !!currentHash &&
      row.assetSha256 === currentHash &&
      // (WS0b P1-3) A row bound to a SUPERSEDED contract is INADMISSIBLE → it falls through to re-QA, which rebinds
      // it to the CURRENT active contract (persistDeliveredQualityEvidence below passes contractHash: activeContractHash)
      // → convergence. Without this, a v1-`passed` row on the current bytes stays admissible while the order is now v2
      // → never re-QA'd → never rebound → readiness loops on contract_stale → QUALITY_REGEN_BUDGET exhaust → refund.
      // (null/null — no frozen contract — is NOT stale, so legacy/flag-off recovery is unchanged.)
      !isQualityEvidenceContractStale(row.contractHash, activeContractHash) &&
      (row.verdict === 'passed' || row.verdict === 'failed');
    if (admissible) {
      // (#6-fix-4 P1 #1) An admissible verdict is trusted as-is (no re-QA), but an admissible FAILED must STILL be
      // rescued: a first-render QA fail (regenCount 0) whose durable 'failed' verdict already matches the current
      // bytes at the current evaluator version would otherwise be skipped here → it never reaches nowFailed → the
      // reserve/regen-rescue never runs → a genuinely failing page ships. Route it to the rescue with its durable
      // regenCount (the processor reserves → clears → redrives, or refunds at budget). An admissible PASS is done.
      if (row!.verdict === 'failed') {
        // (release c-ii) The SHARED outcome decides release / park / rescue AND the park kind — evaluateQualityGate
        // consumes the identical struct, so gate and recovery cannot disagree on any dimension. A byte-bound
        // safety-only release CLEARS (nowPassed); a hard-hold (safety unless released, or contract_world) PARKS with
        // the shared kind — a mixed safety:+contract_world: release parks as contract_world in BOTH; anything else is
        // the regen-rescue. This is already the admissible-failed path, matching the gate's admissibility.
        const h = resolveArtifactHoldOutcome(row!, currentHash, { contractVersion: QUALITY_EVALUATOR_CONTRACT_VERSION, activeContractHash });
        if (h.released) result.nowPassed.push(art.artifactKey);
        else if (h.hardHold && h.kind) notePark(art.artifactKey, h.kind);
        else result.nowFailed.push({ artifactKey: art.artifactKey, regenCount: row!.regenCount });
      }
      continue;
    }

    const storedCtx = (row?.evidence as { qaContext?: QaContext | null } | null)?.qaContext ?? undefined;
    // (#6-fix-3 BLOCKER 1) No stored context → we CANNOT re-QA against the real requirements, and we must NEVER
    // fabricate a lenient context (that could PASS a page missing its required companion/crib/family). Leave it
    // evidence_unknown (fail-closed) → the recommit blocks → recovery/refund. The producer now persists the exact
    // context ATOMICALLY with the delivered asset, so a real delivered artifact always has its context and this
    // branch is only hit for a genuinely context-less row (never auto-passed under weaker requirements).
    if (!storedCtx) {
      result.stillUnknown.push(art.artifactKey);
      continue;
    }

    // (Slice A) Merge the page's current world expectation so the re-QA runs world QA (else an old row's stored
    // context lacks it → re-QA passes visually → ships un-world-QA'd, defeating the qa-v2 bump).
    const world = worldByArt.get(art.artifactKey);
    const reQaCtx: QaContext = world ? { ...storedCtx, worldExpectation: world } : storedCtx;

    result.reQaCount += 1;
    await persistDeliveredQualityEvidence(
      prisma,
      {
        orderId,
        artifactKey: art.artifactKey,
        deliveredUrl: art.deliveredUrl,
        presentationApplied: true, // force a fresh Vision pass on the CURRENT stored URL; never reuse a raw verdict
        rawVerdict: undefined,
        qaContext: reQaCtx,
        regenAttempts: null,
        // (WS0b B1) Re-bind the re-QA'd evidence to the Order's CURRENT active contract (deliberate recovery re-bind).
        contractHash: activeContractHash,
      },
      deps,
    );

    const fresh = await prisma.qualityEvidence.findUnique({
      where: { orderId_artifactKey: { orderId, artifactKey: art.artifactKey } },
      select: {
        verdict: true, regenCount: true, reason: true,
        evaluatorContractVersion: true, assetSha256: true, contractHash: true, safetyOverride: true, safetyOverrideSha256: true,
      },
    });
    if (fresh?.verdict === 'passed') result.nowPassed.push(art.artifactKey);
    // (Slice A / Stage 1) A contract-world drift OR a physical-safety hazard → PARK (terminal human QA), not rescue.
    // The fresh re-QA cleared any override (P1b), so the shared outcome's kind is the plain safety-dominates classification.
    else if (fresh?.verdict === 'failed') {
      const h = resolveArtifactHoldOutcome(fresh, currentHash, { contractVersion: QUALITY_EVALUATOR_CONTRACT_VERSION, activeContractHash });
      if (h.hardHold && h.kind) notePark(art.artifactKey, h.kind);
      else result.nowFailed.push({ artifactKey: art.artifactKey, regenCount: fresh.regenCount });
    }
    else result.stillUnknown.push(art.artifactKey);
  }
  return result;
}

/**
 * (#6-fix-3 BLOCKER 3) The artifact keys durably marked `regenPending` — cleared for a regen and awaiting a
 * re-render. Set atomically with the clear by reserveMarkAndClearRegen; survives a redrive that never started, so
 * the exception-processor re-dispatches from this marker on the next tick instead of refunding a destroyed asset.
 * Cleared once the re-rendered bytes are re-QA'd (persistDeliveredQualityEvidence overwrites the evidence JSON).
 */
export async function loadRegenPendingArtifacts(prisma: PrismaClient, orderId: string): Promise<string[]> {
  const rows = await prisma.qualityEvidence.findMany({
    where: { orderId },
    select: { artifactKey: true, evidence: true },
  });
  return rows
    .filter((r) => {
      const e = r.evidence;
      return !!e && typeof e === 'object' && !Array.isArray(e) && (e as Record<string, unknown>).regenPending === true;
    })
    .map((r) => r.artifactKey);
}
