/**
 * #7-a 6 — exception-processor recovery for infra_transient(quality_evidence_unknown).
 *
 * #6-fix (Codex gate): recovery must enumerate the REQUIRED artifacts (cover + every page), NOT just the
 * existing evidence rows. For each required artifact whose evidence is MISSING, stale, hash-mismatched vs the
 * CURRENT delivered bytes (presentationUrl ?? url), or evidence_unknown → re-QA the CURRENT delivered bytes
 * (ZERO renders — inspectAsset + evaluatePageVisualQa on the stored URL) and persist a fresh verdict bound to
 * the current hash (the persist preserves the DB-reserved regenCount). This recovers a RECOVERABLE current
 * image (a crash-envelope missing row, or a stale PASS row that no longer matches the swapped bytes) instead of
 * refunding it. The refreshed verdicts then feed the recommit (resolve / quality_failed upgrade / re-block) and
 * the regen-rescue (a failed artifact with budget remaining is regenerated by the processor).
 */
import type { PrismaClient } from '@prisma/client';
import { inspectAsset } from './asset-integrity';
import { evaluatePageVisualQa } from './page-visual-qa';
import {
  persistDeliveredQualityEvidence,
  type QaContext,
  type ProducerDeps,
} from './quality-evidence-producer';
import { QUALITY_EVALUATOR_CONTRACT_VERSION, coverArtifactKey, pageArtifactKey } from './quality-evidence';

export interface QualityRecoveryResult {
  reQaCount: number;
  nowPassed: string[];
  /** artifacts that re-QA'd to a deterministic FAIL, with their durable regenCount (drives the regen-rescue). */
  nowFailed: Array<{ artifactKey: string; regenCount: number }>;
  stillUnknown: string[];
}

// Fallback QA context for a required artifact with NO stored context (a crash-envelope missing row). Strict by
// design — a personalized children's book expects the child on the cover AND every page — so it can NEVER
// FABRICATE a pass (it only adds the positive child requirement); at worst it over-refunds a rare child-absent
// crash-envelope page. Rows that exist (evidence_unknown/stale/hash-mismatch) carry their real stored context.
const FALLBACK_QA_CONTEXT: QaContext = {
  expectsChild: true,
  expectsCompanion: false,
  expectedPageTimeOfDay: null,
  isEmotionalClosing: false,
  hasStructuredObjects: false,
  hasRailedBedOrCrib: false,
  hasHumanFamily: false,
};

interface RequiredArtifact {
  artifactKey: string;
  deliveredUrl: string;
}

/** The REQUIRED artifacts with CURRENT delivered bytes: cover (GeneratedBook.coverImageUrl) + each page
 *  (imageAsset.presentationUrl ?? url). Artifacts with no bytes yet are the integrity gate's concern, not QA. */
async function loadRequiredArtifacts(prisma: PrismaClient, orderId: string): Promise<RequiredArtifact[]> {
  const order = await prisma.order.findUnique({
    where: { id: orderId },
    select: {
      book: {
        select: {
          coverImageUrl: true,
          pages: {
            orderBy: { pageNumber: 'asc' },
            select: { pageNumber: true, imageAsset: { select: { url: true, presentationUrl: true } } },
          },
        },
      },
    },
  });
  const out: RequiredArtifact[] = [];
  const cover = order?.book?.coverImageUrl?.trim();
  if (cover) out.push({ artifactKey: coverArtifactKey(), deliveredUrl: cover });
  for (const p of order?.book?.pages ?? []) {
    const url = (p.imageAsset?.presentationUrl ?? p.imageAsset?.url)?.trim();
    if (url) out.push({ artifactKey: pageArtifactKey(p.pageNumber), deliveredUrl: url });
  }
  return out;
}

export async function reQaUnknownQualityEvidence(
  prisma: PrismaClient,
  orderId: string,
  deps: ProducerDeps = {},
): Promise<QualityRecoveryResult> {
  const inspect = deps.inspect ?? inspectAsset;
  const required = await loadRequiredArtifacts(prisma, orderId);
  const rows = await prisma.qualityEvidence.findMany({
    where: { orderId },
    select: { artifactKey: true, verdict: true, evaluatorContractVersion: true, assetSha256: true, evidence: true },
  });
  const byKey = new Map(rows.map((r) => [r.artifactKey, r]));

  const result: QualityRecoveryResult = { reQaCount: 0, nowPassed: [], nowFailed: [], stillUnknown: [] };
  for (const art of required) {
    const currentHash = (await inspect(art.deliveredUrl)).sha256;
    const row = byKey.get(art.artifactKey);
    // Admissible = a durable passed/failed verdict on the CURRENT bytes at the current evaluator version. Anything
    // else (missing row, stale version, hash mismatch vs current bytes, or evidence_unknown) is re-QA'd.
    const admissible =
      !!row &&
      row.evaluatorContractVersion === QUALITY_EVALUATOR_CONTRACT_VERSION &&
      !!currentHash &&
      row.assetSha256 === currentHash &&
      (row.verdict === 'passed' || row.verdict === 'failed');
    if (admissible) continue;

    result.reQaCount += 1;
    const storedCtx = (row?.evidence as { qaContext?: QaContext | null } | null)?.qaContext ?? undefined;
    await persistDeliveredQualityEvidence(
      prisma,
      {
        orderId,
        artifactKey: art.artifactKey,
        deliveredUrl: art.deliveredUrl,
        presentationApplied: true, // force a fresh Vision pass on the CURRENT stored URL; never reuse a raw verdict
        rawVerdict: undefined,
        qaContext: storedCtx ?? FALLBACK_QA_CONTEXT,
        regenAttempts: null,
      },
      deps,
    );

    const fresh = await prisma.qualityEvidence.findUnique({
      where: { orderId_artifactKey: { orderId, artifactKey: art.artifactKey } },
      select: { verdict: true, regenCount: true },
    });
    if (fresh?.verdict === 'passed') result.nowPassed.push(art.artifactKey);
    else if (fresh?.verdict === 'failed') result.nowFailed.push({ artifactKey: art.artifactKey, regenCount: fresh.regenCount });
    else result.stillUnknown.push(art.artifactKey);
  }
  return result;
}
