/**
 * #7-a 6 — exception-processor recovery for infra_transient(quality_evidence_unknown).
 *
 * #6-fix (Codex gate): recovery must enumerate the REQUIRED artifacts (cover + every page), NOT just the
 * existing evidence rows. For each required artifact whose evidence is MISSING, stale, hash-mismatched vs the
 * CURRENT delivered bytes (presentationUrl ?? url), or evidence_unknown → re-QA the CURRENT delivered bytes
 * (ZERO renders — inspectAsset + evaluatePageVisualQa on the stored URL) and persist a fresh verdict bound to
 * the current hash (the persist preserves the DB-reserved regenCount). This recovers a RECOVERABLE current
 * image (a crash-envelope missing row, or a stale PASS row that no longer matches the swapped bytes) instead of
 * refunding it. The refreshed verdicts then feed the recommit (resolve / quality_failed upgrade / re-block) and
 * the regen-rescue (a failed artifact with budget remaining is regenerated by the processor).
 */
import type { PrismaClient } from '@prisma/client';
import { inspectAsset } from './asset-integrity';
import { evaluatePageVisualQa } from './page-visual-qa';
import {
  persistDeliveredQualityEvidence,
  type QaContext,
  type ProducerDeps,
} from './quality-evidence-producer';
import { QUALITY_EVALUATOR_CONTRACT_VERSION, coverArtifactKey, pageArtifactKey } from './quality-evidence';

export interface QualityRecoveryResult {
  reQaCount: number;
  nowPassed: string[];
  /** artifacts that re-QA'd to a deterministic FAIL, with their durable regenCount (drives the regen-rescue). */
  nowFailed: Array<{ artifactKey: string; regenCount: number }>;
  stillUnknown: string[];
}

interface RequiredArtifact {
  artifactKey: string;
  deliveredUrl: string;
}

/** The REQUIRED artifacts with CURRENT delivered bytes: cover (GeneratedBook.coverImageUrl) + each page
 *  (imageAsset.presentationUrl ?? url). Artifacts with no bytes yet are the integrity gate's concern, not QA. */
async function loadRequiredArtifacts(prisma: PrismaClient, orderId: string): Promise<RequiredArtifact[]> {
  const order = await prisma.order.findUnique({
    where: { id: orderId },
    select: {
      book: {
        select: {
          coverImageUrl: true,
          pages: {
            orderBy: { pageNumber: 'asc' },
            select: { pageNumber: true, imageAsset: { select: { url: true, presentationUrl: true } } },
          },
        },
      },
    },
  });
  const out: RequiredArtifact[] = [];
  const cover = order?.book?.coverImageUrl?.trim();
  if (cover) out.push({ artifactKey: coverArtifactKey(), deliveredUrl: cover });
  for (const p of order?.book?.pages ?? []) {
    const url = (p.imageAsset?.presentationUrl ?? p.imageAsset?.url)?.trim();
    if (url) out.push({ artifactKey: pageArtifactKey(p.pageNumber), deliveredUrl: url });
  }
  return out;
}

export async function reQaUnknownQualityEvidence(
  prisma: PrismaClient,
  orderId: string,
  deps: ProducerDeps = {},
): Promise<QualityRecoveryResult> {
  const inspect = deps.inspect ?? inspectAsset;
  const required = await loadRequiredArtifacts(prisma, orderId);
  const rows = await prisma.qualityEvidence.findMany({
    where: { orderId },
    select: { artifactKey: true, verdict: true, evaluatorContractVersion: true, assetSha256: true, regenCount: true, evidence: true },
  });
  const byKey = new Map(rows.map((r) => [r.artifactKey, r]));

  const result: QualityRecoveryResult = { reQaCount: 0, nowPassed: [], nowFailed: [], stillUnknown: [] };
  for (const art of required) {
    const currentHash = (await inspect(art.deliveredUrl)).sha256;
    const row = byKey.get(art.artifactKey);
    // Admissible = a durable passed/failed verdict on the CURRENT bytes at the current evaluator version. Anything
    // else (missing row, stale version, hash mismatch vs current bytes, or evidence_unknown) is re-QA'd.
    const admissible =
      !!row &&
      row.evaluatorContractVersion === QUALITY_EVALUATOR_CONTRACT_VERSION &&
      !!currentHash &&
      row.assetSha256 === currentHash &&
      (row.verdict === 'passed' || row.verdict === 'failed');
    if (admissible) {
      // (#6-fix-4 P1 #1) An admissible verdict is trusted as-is (no re-QA), but an admissible FAILED must STILL be
      // rescued: a first-render QA fail (regenCount 0) whose durable 'failed' verdict already matches the current
      // bytes at the current evaluator version would otherwise be skipped here → it never reaches nowFailed → the
      // reserve/regen-rescue never runs → a genuinely failing page ships. Route it to the rescue with its durable
      // regenCount (the processor reserves → clears → redrives, or refunds at budget). An admissible PASS is done.
      if (row!.verdict === 'failed') {
        result.nowFailed.push({ artifactKey: art.artifactKey, regenCount: row!.regenCount });
      }
      continue;
    }

    const storedCtx = (row?.evidence as { qaContext?: QaContext | null } | null)?.qaContext ?? undefined;
    // (#6-fix-3 BLOCKER 1) No stored context → we CANNOT re-QA against the real requirements, and we must NEVER
    // fabricate a lenient context (that could PASS a page missing its required companion/crib/family). Leave it
    // evidence_unknown (fail-closed) → the recommit blocks → recovery/refund. The producer now persists the exact
    // context ATOMICALLY with the delivered asset, so a real delivered artifact always has its context and this
    // branch is only hit for a genuinely context-less row (never auto-passed under weaker requirements).
    if (!storedCtx) {
      result.stillUnknown.push(art.artifactKey);
      continue;
    }

    result.reQaCount += 1;
    await persistDeliveredQualityEvidence(
      prisma,
      {
        orderId,
        artifactKey: art.artifactKey,
        deliveredUrl: art.deliveredUrl,
        presentationApplied: true, // force a fresh Vision pass on the CURRENT stored URL; never reuse a raw verdict
        rawVerdict: undefined,
        qaContext: storedCtx,
        regenAttempts: null,
      },
      deps,
    );

    const fresh = await prisma.qualityEvidence.findUnique({
      where: { orderId_artifactKey: { orderId, artifactKey: art.artifactKey } },
      select: { verdict: true, regenCount: true },
    });
    if (fresh?.verdict === 'passed') result.nowPassed.push(art.artifactKey);
    else if (fresh?.verdict === 'failed') result.nowFailed.push({ artifactKey: art.artifactKey, regenCount: fresh.regenCount });
    else result.stillUnknown.push(art.artifactKey);
  }
  return result;
}

/**
 * (#6-fix-3 BLOCKER 3) The artifact keys durably marked `regenPending` — cleared for a regen and awaiting a
 * re-render. Set atomically with the clear by reserveMarkAndClearRegen; survives a redrive that never started, so
 * the exception-processor re-dispatches from this marker on the next tick instead of refunding a destroyed asset.
 * Cleared once the re-rendered bytes are re-QA'd (persistDeliveredQualityEvidence overwrites the evidence JSON).
 */
export async function loadRegenPendingArtifacts(prisma: PrismaClient, orderId: string): Promise<string[]> {
  const rows = await prisma.qualityEvidence.findMany({
    where: { orderId },
    select: { artifactKey: true, evidence: true },
  });
  return rows
    .filter((r) => {
      const e = r.evidence;
      return !!e && typeof e === 'object' && !Array.isArray(e) && (e as Record<string, unknown>).regenPending === true;
    })
    .map((r) => r.artifactKey);
}
